
// import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import Head from 'next/head'
import TopBar from '@/components/TopBar/TopBar'
import ThemeContextProvider from '@/context/ThemeContext'
import { AppProps } from 'next/app'

// const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>Countries API</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link rel='icon' href='/icon.png' />
      </Head>

      <ThemeContextProvider>
        <TopBar />

        <Component {...pageProps} />
      </ThemeContextProvider>
    </>
  )
}