import TopBar from '@/components/TopBar/TopBar'
import '../styles/globals.scss'
import ThemeContextProvider from '@/context/ThemeContext'
import { Suspense } from 'react'
import MainLoader from '@/components/Loaders/MainLoader'

export const metadata = {
  title: 'Countries API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <ThemeContextProvider>
          <TopBar />
          <Suspense fallback={<MainLoader />}>
            {children}
          </Suspense>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
